### ISSUE TITLE
Attempt to postMessage on disconnected port...

### ISSUE THREAD

**Issue by zelad** [mdn/webextensions-examples#266] opened 2017-08-15 10:28 UTC
I don't understand using temporary loading I get this error message:

> Could not map contract ID '@mozilla.org/fxaccounts/push;1' to CID {1b7db999-2ecd-4abf-bb95-> > a726896798ca} because no implementation of the CID is registered.  components.manifest:175
Use of nsIFile in content process is deprecated.  loader.js:281:6

> Sending:  ping  background.js:17:3

> Attempt to postMessage on disconnected port
![12_25_33](https://user-images.githubusercontent.com/985907/29312324-15c6a84c-81b5-11e7-8258-9fd75d99aba9.png)

Thanks!

**Comment by wbamberg** [comment] 2017-08-15 12:54
Which example are you referring to, please?

**Comment by zelad** [comment] 2017-08-15 13:04
Oops sorry!
this one:
native-messaging

Thank you for your attention
😊

2017-08-15 14:54 GMT+02:00 wbamberg <notifications@github.com>:

**Comment by wbamberg** [comment] 2017-08-18 04:40
This is working for me. I've tested with Firefoxes 55.0.2 and 57.0a1, on Mac OS X.

Could you please let me know the Firefox version and platform you have, and please confirm that you've followed the setup steps listed in the README: https://github.com/mdn/webextensions-examples/tree/master/native-messaging#setup. Also, do you see any other errors in the console?

**Comment by zelad** [comment] 2017-08-19 16:25
I confirme, i've followed the steps listed in README...
I've tested with Firefoxes 55.02 and 56.0b3 Developer edition on 32 bits, on Windows 10...
I'vnot other errors in the console...

**Comment by wbamberg** [comment] 2017-08-23 04:32
@andymckay , do you know anyone on Windows who could try to reproduce this? It works for me on OS X...

**Comment by BojanKogoj** [comment] 2017-08-27 12:01
@wbamberg I got the same result on windows 10.

![Attempt to postMessage on disconnected port](https://user-images.githubusercontent.com/634075/29749575-06dec4b6-8b30-11e7-9c2b-c28322feaaaa.png)

**Comment by mortepcandvr** [comment] 2017-09-17 15:39
Same issue for me on Windows 7 x64, on Firefox 55.03 (32bit)
![2017-09-18 01_26_29-developer tools - native messaging example - __generated_background_page html](https://user-images.githubusercontent.com/16718409/30522288-efd63df2-9c10-11e7-93ee-eb49b363fb4d.png)
Followed all customisation/setup steps in README
[https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging#Setup](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging#Setup)
-Customised ping_pong_win.bat, ping_pong.json to match correct subdir
-Created and ran a reg add batch file as admin, 
-Confirmed in regedit that correct key had been added.
-Tried both python 2.7 & python 3.6.2
-Tried restarting Firefox with no add-ons in Safe mode before temp load of native-messaging webextension but that just got an error in console when attempting to temp load from about:debugging

**Comment by cmoon2000** [comment] 2017-09-23 06:31
I had same problem.  Maybe you're doing wrong at step 4 "Add a registry key".
Just add command to cmd or powershell:

`REG ADD "HKEY_CURRENT_USER\SOFTWARE\Mozilla\NativeMessagingHosts\ping_pong" /ve /d "C:\path\to\ping_pong.json" /f`

![capture](https://user-images.githubusercontent.com/6170794/30770780-72b316e0-a063-11e7-92dc-00531e8e889d.PNG)

**Comment by mortepcandvr** [comment] 2017-09-23 15:59
For my case, I did confirm the registry entry per my checklist in comment, but I'll paste here to ensure it looks right
![image](https://user-images.githubusercontent.com/16718409/30774764-6a4db16e-a0cb-11e7-8f51-e0e0ccd79b08.png)


cut n pasting backwards directly from that registry key value, into explorer, 
shows that it is definitely the correct subdir on my drive:
```
D:\users\morte\downloads\CloudStation\dev\webextensions\native-messaging\app>dir
 Volume in drive D is morte3T03a
 Volume Serial Number is C8B2-7C9E

 Directory of D:\users\morte\downloads\CloudStation\dev\webextensions\native-messaging\app

2017-09-18  00:51    <DIR>          .
2017-09-18  00:51    <DIR>          ..
2017-09-18  00:49               264 ping_pong.json
2017-09-18  00:49               255 ping_pong.json~
2017-09-18  00:43             2,129 ping_pong.py
2017-09-18  00:51               188 ping_pong_regadd.bat
2017-09-18  00:51                 0 ping_pong_regadd.bat~
2017-09-18  01:20               118 ping_pong_win.bat
               6 File(s)          2,954 bytes
               2 Dir(s)  225,050,148,864 bytes free
```

**Comment by cmoon2000** [comment] 2017-09-24 08:35
Have you tried in ping_pong.json, replace
`"path": "/path/to/native-messaging/app/ping_pong.py"` to
`"path": "/path/to/native-messaging/app/ping_pong.bat"`
It's an alternative to run script by bat file.

Following the guide [native messaging](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging#App_manifest_location)
![screenshot-2017-9-24 native messaging](https://user-images.githubusercontent.com/6170794/30780754-c3d6feb8-a13c-11e7-876f-5f902d28c091.png)

**Comment by andymckay** [comment] 2017-09-25 15:47
I tried this out on Windows 10 and when I had a typo in my `ping_pong.json` I was able to reproduce this port disconnect error. Once I fixed that it worked fine. I'll see if I can write a quick Python script to check the setup and spot this sort of problem.

**Comment by mortepcandvr** [comment] 2017-09-26 00:13
Thanks to two last commenters @cmoon2000, @andymckay !   
I am greatly ashamed to admit I changed all the \ to \\ for the path in ping_pong.json, 
but neglected to change ping_pong.py to ping_pong_win.bat

Sure enough, working now!

![image](https://user-images.githubusercontent.com/16718409/30836708-35383614-a2a3-11e7-85f1-34282a33c11f.png)

**Comment by wbamberg** [comment] 2017-10-25 20:59
Closing, since this seems to be user error (at least for people who have had this problem recently).

**Closed by wbamberg** 2017-10-25 20:59 UTC

**Comment by eug48** [comment] 2018-03-01 13:04
In case this helps someone: check the **Browser** Console (Firefox Menu --> Web Developer --> Browser Console). I was getting this error since I was trying to use the same manifest.json as for Chrome and Firefox wasn't liking the allowed_origins.... (https://bugzilla.mozilla.org/show_bug.cgi?id=1361459)

**Comment by zaunerp** [comment] 2023-05-16 17:08
Hello,
I also have such error but from a diffrent file. I get this error in my React Application. Can anyone help?

![react-moz-postMessage-error](https://github.com/mdn/webextensions-examples/assets/112475045/17da67ab-00f9-490c-b075-59a493521ed3)

**Comment by nathub** [comment] 2025-07-15 22:12
I am getting a lot of this error while I watch Twitch streams
