### ISSUE TITLE
Webextension panel does not auto-resize according to the URLs length 

### ISSUE THREAD

**Issue by vasilicamihasca** [mdn/webextensions-examples#90] opened 2016-09-06 14:07 UTC
**Steps to reproduce:**
1.Install the following webextension as a temporary add-on:
[history-deleter.zip](https://github.com/mdn/webextensions-examples/files/456875/history-deleter.zip)
2.Navigate a bit through google images in order to gather some browsing history.

**Expected results:**
The entire content is correctly displayed in the panel.

**Actual results:**
When the URLs are too long the webextension panel does not auto-resize according to the links length and the last 5 visited sites are not entirely displayed.

**Additional notes:**
- This issue reproduces on Firefox 51.0a1 (2016-09-05) and Firefox 50.0a2 (2016-09-05) under Windows 10 64-bit.
- Please see the attached screenshot:
![2016-09-06_1701](https://cloud.githubusercontent.com/assets/18114210/18276563/114d87e6-7454-11e6-9c39-d4c49b4c2d17.png)

**Comment by andymckay** [comment] 2016-09-20 20:07
Yeah that's not great but I wanted to keep the add-on really simple and the focus of the add-on is on the history deleter API not on the length. Saying that if, someone wanted to send a really simple pull request that fixed this, that would be cool.

**Comment by kartik95** [comment] 2016-10-12 12:48
Fixed the bug. Pull request https://github.com/mdn/webextensions-examples/pull/101

**Comment by kartik95** [comment] 2016-10-13 10:13
Will my PR be merged anytime soon? Or does it need any changes? @andymckay 
I request you to please add 'hacktoberfest' label to this issue before merging. It would really help me. Thanks!

**Comment by wbamberg** [comment] 2016-10-13 17:29
Fixed by https://github.com/mdn/webextensions-examples/pull/101.

**Comment by wbamberg** [comment] 2016-10-13 17:30
@vasilicamihasca , could you verify the fix, please?

**Comment by vasilicamihasca** [comment] 2016-10-14 16:02
I am still able to reproduce this issue on Firefox 51.0a2 (2016-10-14) under Windows 10 64-bit.

![2016-10-14_1848](https://cloud.githubusercontent.com/assets/18114210/19394104/57b97028-9240-11e6-90f3-7799653f0df9.png)

I am not sure but it might be a regression here. Because I noticed that on Firefox 49.0.1 successfully appears a scrollbar and the URL’s are correctly displayed.

![2016-10-14_1853_001](https://cloud.githubusercontent.com/assets/18114210/19394113/5d09016a-9240-11e6-877b-1c57cfe6243f.png)

**Comment by wbamberg** [comment] 2016-10-14 18:42
Yes, I see this too. I think we should file a Firefox bug for this. @vasilicamihasca , since you found it, do you mind filing?

**Comment by vasilicamihasca** [comment] 2016-10-18 08:47
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1310947

**Comment by wbamberg** [comment] 2016-10-18 17:38
Thanks @vasilicamihasca ! Since this is confirmed as a Firefox bug, we can close this. Thanks also @kartik95 for improving the look of the panel in the example.

**Closed by wbamberg** 2016-10-18 17:38 UTC
Labels: good first bug, hacktoberfest
