### ISSUE TITLE
context-menu-demo throws "Extension is invalid"

### ISSUE THREAD

**Issue by edomato** [mdn/webextensions-examples#172] opened 2017-01-02 17:15 UTC
When trying to load the extension through about:debugging the browser throws:

"There was an error during installation: Extension is invalid"

And the console says:

Error: Extension is invalid
Stack trace:
loadManifestFromWebManifest<@resource://gre/modules/addons/XPIProvider.jsm:907:11
TaskImpl_run@resource://gre/modules/Task.jsm:319:40
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:937:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:816:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:750:11
  controls.js:59:9
	loadAddonFromFile/< resource://devtools/client/aboutdebugging/components/addons/controls.js:59:9
	Handler.prototype.process resource://gre/modules/Promise-backend.js:940:21
	this.PromiseWalker.walkerLoop resource://gre/modules/Promise-backend.js:816:7
	this.PromiseWalker.scheduleWalkerLoop/< resource://gre/modules/Promise-backend.js:750:11

**Comment by rpl** [comment] 2017-01-02 17:32
@edomato on which Firefox version?

I just tried on Firefox 50.1.0, DevEdition (52.0a2) and Nightly (53) and it seems to work as expected (the extension loaded correctly and it is listed in the about:debugging/about:addons pages and its context menu has been added).

**Comment by edomato** [comment] 2017-01-02 17:54
I'm trying it also with version 50.1.0 but is from the Debian GNU/Linux repositories.

Maybe something is missing in this compilation?.

I tried other extensions and they worked fine. :-(

**Comment by rpl** [comment] 2017-01-02 18:08
@edomato that's pretty strange, I'm testing it on Ubuntu (it is a different build but it is still weird that it would behave differently)

Can you download a DevEdition and give it a try on your system?

You can download it from https://www.mozilla.org/en-US/firefox/developer/ and it creates a different profile by default and so it would not affect your regular Firefox profile.

Let me know how it goes!

**Comment by edomato** [comment] 2017-01-02 18:48
Ok, I tested with DevEdition and it throws the same, but at least now I see a message that I understand on my command line :-)

1483382638187	addons.webextension.<unknown>	ERROR	Loading extension 'null': Reading manifest: Value for "default_locale" property must correspond to a directory in "_locales/". Not found: "_locales/en/"

The weirdest thing is that the "_locales/en/" directory does exists since I'm trying to test the extension from a clone of this github repository without any chage.

**Comment by rpl** [comment] 2017-01-02 18:55
@edomato Thanks for testing it! 
Locally I was testing it using the [web-ext](https://github.com/mozilla/web-ext) command line tool.

It is definitely weird, but at least we have narrowed down the issue and now we have more useful information about it, I'm going to try it locally again by installing the example using the about:debugging page and tracking down this weird issue.

Can you try to use the web-ext command line tool and just to confirm that it works correctly for you like it does on my system?

**Comment by edomato** [comment] 2017-01-03 14:43
Ok, I tested with the latest LTS nodejs/npm version downloaded from nodejs website and after installing web-ext and trying the extension it failed with the following message:

```
Running web extension from /home/test/github/webextensions-examples/context-menu-demo
Running Firefox with profile at /tmp/8edc4a79-0605-4618-a46b-e7fcb010023b
Use --verbose or open Tools > Web Developer > Browser Console to see logging

run: WebExtError: installTemporaryAddon: Error: unknownError: Could not install add-on at '/home/test/github/webextensions-examples/context-menu-demo': Error: Extension is invalid
    at /usr/local/lib/node_modules/web-ext/dist/webpack:/src/firefox/remote.js:9:5460
    at EventEmitter.handleMessage (/usr/local/lib/node_modules/web-ext/node_modules/firefox-client/lib/client.js:161:7)
    at EventEmitter.readMessage (/usr/local/lib/node_modules/web-ext/node_modules/firefox-client/lib/client.js:220:10)
    at EventEmitter.onData (/usr/local/lib/node_modules/web-ext/node_modules/firefox-client/lib/client.js:186:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)

```

**Comment by edomato** [comment] 2017-01-03 15:11
Just to let you know, I tested web-ext with other extension from the examples and it worked fine.

I wanted to discard that maybe I had an issue with my web-ext installation :-)

**Comment by frostschutz** [comment] 2017-02-17 15:11
Should be a bug in firefox (nightly), perhaps only affecting linux?

I have the same issue (`Not found: "_locales/en/"`), with any webextension that uses locale, when trying to load it via about:debugging. But only if that extension resides in my homedir. If I `rsync -a` it to `/tmp/` I can load it fine from there. According to strace it actually found the dir but still complains about it... not sure where to report it / how to debug it...

**Comment by wbamberg** [comment] 2017-02-17 17:08
@frostschutz , would you mind filing a Firefox bug for this: https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit&component=WebExtensions%3A%20Untriaged ?

**Comment by frostschutz** [comment] 2017-02-27 18:04
Actually it seems only my Gentoo box is affected... can't reproduce it on Ubuntu/ArchLinux no matter how I try. I guess it's something weird on my end...

**Comment by frostschutz** [comment] 2017-02-28 14:46
Using the Debugger a bit more it turns out that OS.File.DirectoryIterator simply returns isDir: false for _locales/{en,de,...} entries on my machine's homedir, even though it is a regular directory... that explains why strace shows firefox assessing these dirs (it does find them after all), they're just ignored further down because "is not a directory" (even though it is).

( A screenshot of the debugger http://imgur.com/a/vSLLZ )

That is so weird...

**Comment by frostschutz** [comment] 2017-03-01 16:58
reported it here https://bugzilla.mozilla.org/show_bug.cgi?id=1343572

**Comment by wbamberg** [comment] 2017-03-01 18:22
Thanks for digging and filing @frostschutz ! I'll close this issue, as it's better tracked over in Bugzilla.

**Closed by wbamberg** 2017-03-01 18:22 UTC
