### ISSUE TITLE
Cursor does not default to address bar when creating new tab

### ISSUE THREAD

**Issue by evliang** [mdn/webextensions-examples#458] opened 2020-09-29 17:28 UTC
When creating a new tab, the cursor starts in the address bar, but when it pops into a new window, the focus does not shift to the new address bar

Expected behavior would be similar to what it is seen on the address bars for Ctrl N / Ctrl + Shift P

**Comment by rpl** [comment] 2021-09-07 17:50
The issue filed in this repo are mainly meant to be related to bugs or improvements to the examples included in this repo (or about WebExtensions APIs already supported on Firefox that do not have yet an example).

Bug reports related to Firefox or Firefox WebExtensions API issue are meant to be filed on bugzilla.mozilla.org (the issue described here seems like it could be a duplicate of [Bug 1411209](https://bugzilla.mozilla.org/show_bug.cgi?id=1411209).

Closing as invalid from this repo perspective.

**Closed by rpl** 2021-09-07 17:50 UTC
Labels: invalid
