### ISSUE TITLE
Browserify can't be used with `tabs.executeScript`

### ISSUE THREAD

**Issue by BigBlueHat** [mdn/webextensions-examples#193] opened 2017-03-10 18:24 UTC
I get this error in the console:
```
Error: Script returned non-structured-clonable data
```

You can test it by browserify-ing an empty file and then using `browser.runtime.executeScript` to attempt to add it to a page.

Webpack's module wrapping code doesn't seem to have this issue.

**Comment by BigBlueHat** [comment] 2017-03-10 18:34
So, it looks like if you create a standalone module, the error is avoided. Though, I'm still digging for how to get these modules (or Webpack modules) to be structured in a way to handle the faux-return value thing (where the file must end with something that's then sent back in the `executeScript` Promise).

**Comment by wbamberg** [comment] 2017-03-12 18:54
@BigBlueHat , if this is a bug, it seems like a bug in Firefox, not in any of these examples. Is that correct?

**Comment by BigBlueHat** [comment] 2017-03-13 13:41
@wbamberg yeah...on further exploration I think you're right...though I'm not sure it's a "bug" so much as a requirement that Firefox has that Chrome (and others maybe) don't have:
> The result values must be structured clonable.
> https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/executeScript#Return_value

However, it's unclear from Chrome's [docs](https://developer.chrome.com/extensions/tabs#method-executeScript) and [info on programmatic injection](https://developer.chrome.com/extensions/content_scripts#pi) what it expects as a return value...apparently anything...maybe.

For this repo, it's probably best just to demo the use of browserify with the requirement of using UMD modules via the `--standalone` option in browserify. Probably just a copy of the webpack-modules one + a content script example.

Thoughts?

**Comment by derwaldgeist** [comment] 2017-04-24 21:06
I ran into the same problem with my extension. Any idea how to work-around this?

**Comment by BigBlueHat** [comment] 2017-04-24 21:16
@derwaldgeist use two executeScript's...one for the dependency and one for your applications code that's formatted in a way to do the return.

Alternatively, you can avoid the who return value thing (which feels very awkward most days...) and use `postMessage()` and friends.

Oh! and one other possible solution for using a single `executeScript` the uses `require` and browserify is to wrap the whole thing in an immediate called function with a return value. Then you get both clarity and lack of cumbersomeness (or...at least less cumbersomeness 😄).

For example...`inject.js`:
```
(function() {
  const nifty = require('...');
  return nifty(true);
})();
```

But then...you may still hit that "structured clonable" thing and have to do some type coercion and such, but at least it's more obvious than ending your code with a variable name all by its lonesome.

Hope that helps!
🎩

**Comment by wbamberg** [comment] 2017-05-08 04:13
Closing this, as it's not a bug in the examples in this repo specifically.

**Closed by wbamberg** 2017-05-08 04:13 UTC
