### ISSUE TITLE
borderify extension does not load into firefox

### ISSUE THREAD

**Issue by romgohan** [mdn/webextensions-examples#196] opened 2017-03-19 16:39 UTC
Windows,  firefox 45.0.2, when I load it with "Load Temporary Add-on" button nothing happens, it does not show on the list. After some unsuccessful tries, I tried with google chrome and it loaded and worked without any problems.

**Comment by wbamberg** [comment] 2017-03-22 14:17
Please try with a recent version of Firefox. I know the README says version 45 should work, but I think it should be corrected to say that you should use the most recent released version, or something like that.

(In this case, I'd guess that the problem is that these examples don't include an explicitly specified add-on ID. See https://developer.mozilla.org/en-US/Add-ons/WebExtensions/WebExtensions_and_the_Add-on_ID).

**Comment by wbamberg** [comment] 2017-03-27 20:39
Fixed by https://github.com/mdn/webextensions-examples/pull/199.

**Closed by wbamberg** 2017-03-27 20:39 UTC
